config/routes.rb
Rails.application.routes.draw do
  # Sign Up requests
  get '/sign-up', to: 'registration#new', as: :registration_new
  post '/sign-up', to: 'registration#create', as: :registration_create

  # Sign In Requests
  get '/sign-in', to: 'sessions#new', as: :sessions_new
  post '/sign-in', to: 'sessions#create', as: :sessions_create
  get '/sign-out', to: 'sessions#destroy', as: :sessions_logout

  # Videos Requests
  get '/videos/edit/:id', to: 'videos#edit', as: :edit_video
  get '/videos/player/:slug', to: 'videos#player', as: :player_video
  delete '/videos/delete/:id', to: 'videos#destroy', as: :delete_video
  put '/videos/update/:id', to: 'videos#update', as: :update_video
  post '/video/:id/view/add', to: 'videos#add_view', as: :add_view_video

  resource :videos
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  validates :name, presence: true
  validates :url, presence: true, format: /.m3u8/i

  belongs_to :user
  has_many :video_views

  def get_views
    self.video_views.count
  end

  def is_same_viewer?(user)
    self.video_views
      .select { |view| 
        puts view.inspect
        view.user_id == user.id
      }
      .any?
  end
end

app/models/video_view.rb
class VideoView < ApplicationRecord
  belongs_to :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  before_action :block_access, only: [:new]
  def new
    @user = User.new
    render "registration/new"
  end

  def create
    user = User.create(user_params)
    if user.save!
      redirect_to :sessions_new, notice: 'Usuario criado com sucesso'
    else
      redirect_to :sessions_new, alert: user.errors.full_messages
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password);
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, only: [:new]

  def create
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      sign_in @user
      redirect_to :videos
    else
      redirect_to :sessions_new, alert: "Usuario e/ou senha invalidos"
    end
  end

  def destroy
    logout
    redirect_to :sessions_new, notice: "Deslogado com sucesso"
  end

  private
  def user_params
    params.require(:user)
      .permit(:email, :password)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :redirect_if_logged_in, except: [:create, :update, :destroy]

  layout "home"

  def show
    @other_videos = Videos::FindOthers.call(current_user) 
  end

  def create
    @video = Videos::Create.call(current_user, video_params)

    if @video.persisted?
      redirect(:videos, { notice: I18n.t(:video_created) })
    else
      redirect(:videos, { alert: @video.errors.full_messages })
    end
  end

  def edit
    @video = Videos::Find.call(current_user, params[:id])
  end

  def update
    video = Videos::Update.call(current_user, params[:id], video_params)
    if video.save
      redirect(:videos, {notice: I18n.t(:video_updated)})
    else
      redirect(:videos, {alert: video.errors.full_messages})
    end
  end

  def destroy
    if Videos::Destroy.call(current_user, params[:id])
      redirect(:videos, {notice: I18n.t(:video_deleted)})
    else
      redirect(:videos, {alert: I18n.t(:video_not_deleted)})
    end
  end

  def player
    @video = Videos::Show.call(params[:slug])
    render "videos/player"
  end

  def add_view
    unless VideoViews::Add.call(params[:id], current_user)
      render :json => {
        :error => I18n.t(:multiple_same_views)
      }, status: 400
    end
  end

  private

  def redirect(destination, flash_hash)
    redirect_to destination, flash_hash 
  end

  def video_params
    params.require(:video).permit(:name, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def block_access
    if current_user.present?
      redirect_to :videos
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def redirect_if_logged_in
    unless logged_in?
      flash[:alert] = "Voce precisa estar logado";
      redirect_to :sessions_new
    end
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/videos_helper.rb
module VideosHelper
  def check_video_user

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoshowMeTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Videoshow.me</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <% if protect_against_forgery? %>
            <meta name="authenticity-token" content="<%= form_authenticity_token %>">
        <% end %>
        <%= stylesheet_link_tag 'application', media: 'all' %>
        <%= javascript_pack_tag 'application' %>
        <link rel="stylesheet" 
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
              integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
              crossorigin="anonymous">
        <link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />
        <link 
            rel="stylesheet" 
            href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" 
            integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" 
            crossorigin="anonymous"
        />

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <%= link_to "videoshow.me", :videos, class: "navbar-brand" %>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                </ul>
                <ul class="navbar-nav my-2 my-lg-0">
                    <li class="nav-item dropdown">
                        <div class="dropdown">
                            <button 
                                class="btn btn-secondary dropdown-toggle" 
                                type="button" id="dropdownMenuButton" 
                                              data-toggle="dropdown">
                                Bem vindo, <%= current_user.name %>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <%= link_to "Sair", :sessions_logout, class: 'dropdown-item'%>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <script 
            src="https://code.jquery.com/jquery-3.5.1.min.js" 
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" 
            crossorigin="anonymous"></script>
        <script 
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" 
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" 
            crossorigin="anonymous"></script>
        <script 
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" 
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" 
            crossorigin="anonymous"></script>

        <script src="https://vjs.zencdn.net/7.8.4/video.js"></script>
        <script src="https://unpkg.com/@videojs/http-streaming@1.13.4/dist/videojs-http-streaming.min.js"></script>
        <%= yield %>
    </body>
</html>

app/views/partials/_alert.html.erb
<% if alert %>
    <% alert.each do |msg| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<% end %>

app/views/partials/_notice.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/videos/components/_other_videos.html.erb
<div class="container">
    <h2>Veja tambem</h2>
    <ul class="list-group list-group-flush">
        <% if @other_videos.any? %>
            <% @other_videos.each do |video| %>
                <li class="list-group-item">
                    <%= link_to video.name, player_video_path(video.slug)%>
                    <span class="badge badge-secondary"><%= video.get_views %></span>
                </li>
            <% end %>
        <% else %>
        Nao ha outros videos
        <% end %>
    </ul>
</div>

app/views/videos/components/_table.html.erb
<table class="table margin-top-3">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nome</th>
            <th scope="col">URL</th>
            <th scope="col">Slug</th>
            <th scope="col">Views</th>
            <th scope="col">Acoes</th>
        </tr>
    </thead>
    <tbody>
        <% if videos.any? %>
            <% videos.each do |video|%>
                <tr>
                    <th scope="row"><%= video.id%></th>
                    <td><%= video.name %></td>
                    <td>
                        <%= link_to video.url, ""%>
                    </td>
                    <td>
                        <%= video.slug %>
                    </td>
                    <td>
                        <%= video.get_views %>
                    </td>
                    <td>
                        <%= render "videos/partials/group_buttons", video: video %>
                    </td>
                </tr>
            <% end %>
        <% else %>
            <tr>
                <th scope="row">#</th>
                <td>Nenhum video encontrado</td>
                <td></td>
                <td></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/videos/edit.html.erb
<div class="container margin-top-3">
    <% if !@video.present? %>
        <h2 class="text-center">Nenhum video foi encontrado</h2>
    <% else %>
    <h2 class="text-center">Editando <%= @video.name %></h2>
        <%= form_with(url: :update_video, method: 'PUT') do |form|%>
            <%= render "videos/partials/inputs", 
                name: @video.name, 
                url: @video.url 
            %>
            <%= form.submit "Salvar", class: "btn-middle btn btn-dark btn-block" %>
        <% end %>
    <% end %>
</div>

app/views/videos/new.html.erb
<div class="container margin-top-3">
    <h2 class="text-center">Criar video</h2>
    <%= form_with(url: :videos, method: 'POST') do |form|%>
        <%= render "videos/partials/inputs", name: nil, url: nil %>
        <%= form.submit "Salvar", class: "btn-middle btn btn-dark btn-block" %>
    <% end %>
</div>

app/views/videos/partials/_group_buttons.html.erb
<div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to "Preview", player_video_path(video.slug), class: "btn btn-secondary"%>
    <%= link_to "Editar", edit_video_path(video.id), class: 'btn btn-dark' %>
    <%= button_to "Deletar", 
        delete_video_path(video.id),
        method: :delete,
        :confirm => "Tem certeza?",
        class: 'btn btn-danger'
    %>
</div>

app/views/videos/partials/_inputs.html.erb
<div class="form-group">
    <div class="input-group">
        <div class="input-group-prepend">
            <div class="input-group-text">
                Nome
            </div> 
        </div> 
        <input 
            type="text" 
            name="video[name]"
            class="form-control"
            value="<%= name ? name : nil %>"
        />
    </div>
</div>
<div class="form-group">
    <div class="input-group">
        <div class="input-group-prepend">
            <div class="input-group-text">
                URL
            </div> 
        </div> 
        <input 
            type="text" 
            name="video[url]"
            class="form-control"
            value="<%= url ? url : nil %>"
        />
    </div>
</div>

app/views/videos/player.html.erb
<div class="container">
    <h2><%= @video.name %></h2>
    <video 
        id="video"
        class="video-js margin-top-3"
        controls
        height="364" 
        width="1140" 
        preload="none" 
        data-video-id="<%= @video.id %>"
        data-setup="{}">
        <source 
            src="<%= @video.url %>" 
            type='application/x-mpegURL'
        >
    </video>    
    <span>
        <i class="far fa-eye"></i> <%= @video.get_views %>
    </span>
</div>
<script charset="utf-8">
    const video = $("video");
    video_id = video.attr('data-video-id');
    var token = $('meta[name="csrf-token"]')[0].content

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': token
        }
    });

    $("video").on('play', event => {
    console.log('played');
      form_data = new FormData();
        
      $.ajax({
        url: `/video/${video_id}/view/add`,
        method: 'POST',
        dataType: 'json',
      });
    })
</script>

app/views/videos/show.html.erb
<div class="container">
    <h2 class="text-center margin-top-3">Meus Videos</h2>
    <%= render "partials/alert" %>
    <%= render "partials/notice" %>
    <%= link_to "Criar Video", :new_videos, class: "btn btn-dark"%>

    <%= render "videos/components/table", videos: current_user.videos %>

    <%= render "videos/components/other_videos", other_videos: @other_videos %>
</div>